 - docker build -t udagram-reverseproxy ./udagram-reverseproxy
 - docker tag udagram-reverseproxy burhanyueksel/udagram-reverseproxy:v1
## Do similar for other three images```
```bash
## Push
## Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push burhanyueksel/udagram-reverseproxy:v1
## Do similar for other three images

 - docker build -t udagram-api-feed ./udagram-api-feed
 - docker tag udagram-api-feed burhanyueksel/udagram-api-feed:v1
## Do similar for other three images```
```bash
## Push
## Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push burhanyueksel/udagram-api-feed:v1
## Do similar for other three images

 - docker build -t udagram-api-user ./udagram-api-user
 - docker tag udagram-api-user burhanyueksel/udagram-api-user:v1
## Do similar for other three images```
```bash
## Push
## Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push burhanyueksel/udagram-api-user:v1
## Do similar for other three images

 - docker build -t udagram-frontend ./udagram-frontend
 - docker tag udagram-frontend burhanyueksel/udagram-frontend:v1
## Do similar for other three images```
```bash
## Push
## Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push burhanyueksel/udagram-frontend:v1
## Do similar for other three images



