 - docker build -t udagram-reverseproxy ./udagram-reverseproxy
 - docker tag udagram-reverseproxy burhanyueksel/udagram-reverseproxy:v1
## Do similar for other three images```
```bash
## Push
## Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push burhanyueksel/udagram-reverseproxy:v1
## Do similar for other three images

