apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
        - name: backend-feed
          image: burhanyueksel/udagram-api-feed
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: POSTGRES_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: POSTGRES_PASSWORD
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: AWS_REGION
            - name: AWS_PROFILE
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: AWS_PROFILE
            - name: AWS_BUCKET
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: AWS_BUCKET
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: JWT_SECRET